import "@/app/global.css"
import ToasterContext from "./context/ToasterContext"
import AuthContext from "./context/AuthContext"
import ActiveStatus from "./components/ActiveStatus"
import { MyThemeContextProvider } from "./context/MyThemeContext"

export const metadata = {
  title: 'Messenger Application',
  description: 'Generated by Facebook',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MyThemeContextProvider>
        <AuthContext>
          <ToasterContext />
          <ActiveStatus />
          {children}
        </AuthContext>
      </MyThemeContextProvider>
      </body>
    </html>
  )
}
